"""empty message

Revision ID: 4db8145bba15
Revises: 
Create Date: 2025-03-04 11:21:54.906098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4db8145bba15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('mem_usage', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('auth_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token', sa.String(length=6), nullable=True),
    sa.Column('reset_token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visitor_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visitor_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_location', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=128), nullable=False),
    sa.Column('original_filename', sa.String(length=128), nullable=False),
    sa.Column('judul', sa.String(length=128), nullable=False),
    sa.Column('nama_penulis', sa.String(length=128), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=True),
    sa.Column('university_name', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('visitor_log')
    op.drop_table('visitor_counter')
    op.drop_table('user')
    op.drop_table('search_query')
    op.drop_table('performance_log')
    op.drop_table('login_attempt')
    # ### end Alembic commands ###
