"""Add view_count column to File model

Revision ID: 55b2ba0c26ea
Revises: 4db8145bba15
Create Date: 2025-03-04 20:41:54.036610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '55b2ba0c26ea'
down_revision = '4db8145bba15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=False, server_default='0'))

    # Set default value for existing records
    op.execute(text("UPDATE file SET view_count = 0 WHERE view_count IS NULL"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
